### ISSUE TITLE
Mac OS X Big Sur (20.3.0) can't build hdf5_test/tid.c.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/vol-tests#10] opened 2021-05-25 20:39 UTC
```
hdf5_test/tid.c:1048:28: error: implicit declaration of
            function 'H5Iregister_future' is invalid in C99 [-Werror,-Wimplicit-fu
            nction-declaration]
```

**Comment by jhendersonHDF** [comment] 2021-05-25 20:51
Are you using a newer commit in the HDF5 develop branch? H5Iregister_future only exists in HDF5 develop, but that code should also be protected such that it only compiles with the develop branch. This might mean that you're using a commit which doesn't yet have the H5Iregister_future changes.

**Comment by hyoklee** [comment] 2021-05-25 20:55
I'm using @qkoziol's  async_vol_register_optional branch of hpc-io/hdf5 repository.

**Comment by jhendersonHDF** [comment] 2021-05-25 21:02
Indeed, it looks like H5Iregister_future doesn't appear in that branch. This may have been intentional to keep separate features in separate branches, but building the VOL tests with that branch will be problematic without H5Iregister_future.

**Comment by qkoziol** [comment] 2021-05-26 18:38
> Indeed, it looks like H5Iregister_future doesn't appear in that branch. This may have been intentional to keep separate features in separate branches, but building the VOL tests with that branch will be problematic without H5Iregister_future.

I believe that the problem is that the vol-tests codes need to include the "hdf5dev.h" header as well as the "hdf5.h" header.

**Comment by jhendersonHDF** [comment] 2021-05-26 19:04
Ah ok, yes that change would need to be made once the hdf5dev.h changes have been merged to develop.

**Comment by derobins** [comment] 2022-08-27 00:18
Including hdf5dev.h is no longer necessary as all the development headers are included via hdf5.h.

**Closed by derobins** 2022-08-27 00:18 UTC
